version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
  push-to-ecr:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: install aws
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
              aws --version
      - run:
          name: login to ECR and push image
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 293362435147.dkr.ecr.us-east-1.amazonaws.com
            docker build -t project-5 .
            docker tag project-5:latest 293362435147.dkr.ecr.us-east-1.amazonaws.com/project-5:latest
            docker push 293362435147.dkr.ecr.us-east-1.amazonaws.com/project-5:latest

  create_cluster:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - run:
          name: install eksctl
          command: |
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
            eksctl create cluster --name project-5 --region=us-east-1 --zones us-east-1a
      - run:
          name: deploy application
          command: |
            kubectl create deploy project-5 --image=293362435147.dkr.ecr.us-east-1.amazonaws.com/project-5:latest

workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      - build-and-test
      - push-to-ecr:
          requires:
            - build-and-test
      - create_cluster:
          requires:
            - push-to-ecr
