version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
  push-to-ecr:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      # - run:
      #     name: install unzip
      #     command: |
      #       yum install -y unzip
      - run:
          name: login to ECR and push image
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 293362435147.dkr.ecr.us-east-1.amazonaws.com
            docker build -t project-5 .
            docker tag project-5:latest 293362435147.dkr.ecr.us-east-1.amazonaws.com/project-5:latest
            docker push 293362435147.dkr.ecr.us-east-1.amazonaws.com/project-5:latest

workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      - build-and-test
      - push-to-ecr:
          requires:
            - build-and-test
