version: 2.1

orbs:
  python: circleci/python@1.5.0
  aws-ecr: circleci/aws-ecr@7.3.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
  push-to-ecr:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: 293362435147.dkr.ecr.us-east-1.amazonaws.com/project-5
          tag: ${CIRCLE_SHA1:0:0},latest-${CIRCLE_BRANCH//\//-}
          extra-build-args: >-
            --progress=plain

workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      - build-and-test
      - push-to-ecr
